###
# Ping sensors
- platform: ping
  host: 192.168.1.1
  name: "router_ping"
- platform: ping
  host: 192.168.1.100
  name: "NASMaster_ping"
- platform: ping
  host: 192.168.1.20
  name: "KidNAS_ping"
- platform: ping
  host: 192.168.1.50
  name: "master_ping"
- platform: ping
  host: 192.168.1.75
  name: "odroid1_ping"
- platform: ping
  host: 192.168.1.80
  name: "odroid2_ping"
- platform: ping
  host: 192.168.1.85
  name: "xiaomi_gw1_ping"
- platform: ping
  host: 192.168.1.86
  name: "xiaomi_humidifier_bedroom_ping"