homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 181
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#logger
logger:
  default: info

# Discover some devices automatically
discovery:

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
#    proxy_url: !secret telegram_bot_proxy_url
#    proxy_params:
#      username: !secret telegram_bot_proxy_username
#      password: !secret telegram_bot_proxy_password
    allowed_chat_ids:
      - !secret telegram_bot_allowed_chat_id_pinkkoff
      - !secret telegram_bot_allowed_chat_id_fludshorty
      - !secret telegram_bot_allowed_chat_id_all

# iOS notifications
ios: !include ios.yaml
notify:
  - name: ios_iphone_all
    platform: group
    services:
      - service: ios_iphone_pinkkoff
      - service: ios_iphone_anechka
  - name: telegram_chat_pinkkoff
    platform: telegram
    chat_id: !secret telegram_bot_allowed_chat_id_pinkkoff
  - name: telegram_chat_fludshorty
    platform: telegram
    chat_id: !secret telegram_bot_allowed_chat_id_fludshorty
  - name: telegram_chat_all
    platform: telegram
    chat_id: !secret telegram_bot_allowed_chat_id_all


# Wake on LAN service
wake_on_lan:


# Sensors
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate

# Fans
fan:
  - platform: xiaomi_miio
    host: 192.168.1.86
    token: !secret xiaomi_humfan_token
    
# Xiaomi gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

# Wheater forecasting
weather:
  - platform: darksky
    name: darksky_forecast
    api_key: !secret dark_sky_api_key

# Climate thermostats
climate:
  - platform: generic_thermostat
    name: thermostat_balcony
    heater: switch.plug_158d00032d5e8b
    target_sensor: sensor.xiaomi_thp_temperature_balcony_158d0002389f84
    min_temp: 1
    max_temp: 30
    ac_mode: false
    target_temp: 10
    cold_tolerance: 1.0
    hot_tolerance: 1.0
    min_cycle_duration:
      minutes: 10
    initial_hvac_mode: "heat"
    away_temp: 3

# Yeelight
yeelight:
  devices:
    192.168.1.87:
      name: yeelight_bedroom_ceiling_light
      model: ceiling13
      nightlight_switch_type: light

#
influxdb:
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  component_config_glob:
    sensor.*humidity*:
      override_measurement: humidity
    sensor.*temperature*:
      override_measurement: temperature
    sensor.*pressure*:
      override_measurement: pressure

# Includes entities
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetimes.yaml
input_text: !include input_texts.yaml
binary_sensor: !include binary_sensors.yaml
