# Weather prediction
- platform: yr
  name: Weather
  #forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

# Уровни заряда батарей
- platform: template
  sensors:
    xiaomi_thp_bedroom_battery:
      friendly_name: "Заряд в датчике THP в комнате"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.xiaomi_thp_temperature_bedroom_158d00025f03f5', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_thp_bathroom_battery:
      friendly_name: "Заряд в датчике THP в ванной"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.xiaomi_thp_temperature_bathroom_158d00025f14c5', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_thp_balcony_battery:
      friendly_name: "Заряд в датчике THP на балконе"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.xiaomi_thp_temperature_balcony_158d0002389f84', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_thp_livingroom_battery:
      friendly_name: "Заряд в датчике THP в гостиной"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.xiaomi_thp_temperature_livingroom_158d00046581b5', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_thp_cloackroom_battery:
      friendly_name: "Заряд в датчике THP в гардеробе"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.xiaomi_thp_temperature_cloackroom_158d0004656f6d', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_thp_corridor_battery:
      friendly_name: "Заряд в датчике THP в коридоре"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('sensor.xiaomi_thp_temperature_corridor_158d000465887b', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_wall_switch_bedroom_battery:
      friendly_name: "Заряд в выключателе в спальне"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_wall_switch_bedroom_158d000230d4a2', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_exit_switch_lobby_battery:
      friendly_name: "Заряд в кнопке на выходе"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_exit_switch_lobby_158d0002135c59', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_water_leak_bedroom_battery:
      friendly_name: "Заряд в датчике протечки 1 в ванной"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_water_leak_bedroom_158d00027b0cd4', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_water_leak_bedroom_2_battery:
      friendly_name: "Заряд в датчике протечки 2 в ванной"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_water_leak_2_bedroom_158d0004a08155', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_water_leak_cloakroom_battery:
      friendly_name: "Заряд в датчике протечки в гардеробе"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_water_leak_cloakroom_158d0004a06fa3', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_water_leak_corridor_battery:
      friendly_name: "Заряд датчика протечки в стояке"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_water_leak_corridor_158d0004a07f44', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_water_leak_livingroom_battery:
      friendly_name: "Заряд в датчике протечки на кухне"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_water_leak_livingroom_158d0004a06f5d', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_motion_bathroom_battery:
      friendly_name: "Заряд в датчике движения в ванной"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_motion_bathroom_158d0002b6e8e6', 'battery_level') }}"
      device_class: battery
- platform: template
  sensors:
    xiaomi_smoke_kitchen_battery:
      friendly_name: "Заряд в датчике дыма на кухне"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('binary_sensor.xiaomi_smoke_kitchen_158d00028229a1', 'battery_level') }}"
      device_class: battery

# Увлажнитель
- platform: template
  sensors:
    xiaomi_humidifier_bedroom_water_level:
      friendly_name: "Уровень воды в увлажнителе"
      unit_of_measurement: '%'
      value_template: "{{ [state_attr('fan.xiaomi_humidifier_bedroom', 'depth') / 1.2, 100] | min | int }}"
      icon_template: "mdi:cup"

# System monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
- platform: command_line
  name: CPU_temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

# Tuya
- platform: template
  sensors:
    tuya_floorheater_bathroom_currtemp:
      friendly_name: "Текущая температура теплого пола"
      value_template: "{{ (state_attr('climate.tuya_floorheater_bathroom', 'current_temperature')) / 2 }}"
      device_class: temperature
      unit_of_measurement: "°C"
- platform: template
  sensors:
    tuya_floorheater_bathroom_currsettemp:
      friendly_name: "Выставленная температура теплого пола"
      value_template: "{{ (state_attr('climate.tuya_floorheater_bathroom', 'temperature')) / 2 }}"
      device_class: temperature
      unit_of_measurement: "°C"