#
# Wake on LAN switch. Indicate working comp
- platform: wake_on_lan
  name: "WoL Master"
  host: "192.168.1.50"
  broadcast_address: "192.168.1.255"
  mac: !secret master_MAC
#
# Xiaomi humidifier dry mode switch
- platform: template
  switches:
    xiaomi_humidifier_bedroom_dry_mode:
      friendly_name: "Режим DRY в увлажнителе в спальне"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier_bedroom', 'dry', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_dry_on 
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
      turn_off:
        service: xiaomi_miio.fan_set_dry_off 
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
